before_install:
  - npm i nan
install:
  - npm run preinstall
script:
  - util/cpplint.sh
  - npm install
language: node_js
node_js:
  - 0.10.48
  - 0.12.18
  - 6.10.0
  - 7.4.0
env:
  - CXX=g++-4.8
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libgphoto2-6
      - libgphoto2-dev
      - libgphoto2-port10
